# Site Settings
title: James Robb
url: 'http://www.jamesrobb.ca'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: James Robb
tagline: "Computer Scientist and Software Engineer "
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

summary: "I am an experienced software engineer in Reykjavik, Iceland that has worked on a wide variety of software and architectural challenges. I hold an MSc in Computer Science and a BSc in Discrete Mathematics/Computer Science. I'm a DIY enthusiast and have been writing code and and building hardware for my own projects for a couple of decades now.<br /><br />Code is a (super cool) tool we use to accomplish higher-level goals and objectives. I enjoy finding and using the right tools to build understandable, testable, and performant solutions to interesting problems."

#sidebar links
email: me@jamesrobb.ca
linkedin: james-robb-15823992
github: jamesrobb
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-109273339-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
